export const heroClasses = {
  root: "hero",
  container: "hero__content",
  copy: "hero__copy",
  visualReveal: "hero__visualReveal",
  visual: {
    root: "hero-visual",
    grid: "hero-visual__grid",
    header: "hero-visual__header",
    eyebrow: "hero-visual__eyebrow",
    status: "hero-visual__status",
    terminal: "hero-visual__terminal",
    terminalBar: "hero-visual__terminalBar",
    terminalDot: "hero-visual__terminalDot",
    terminalBody: "hero-visual__terminalBody",
    terminalLine: "hero-visual__terminalLine",
    terminalCommand: "hero-visual__terminalCommand",
    cards: "hero-visual__cards",
    card: "hero-visual__card",
    cardLabel: "hero-visual__cardLabel",
    cardValue: "hero-visual__cardValue",
    rail: "hero-visual__rail",
    railTrack: "hero-visual__railTrack",
    railFill: "hero-visual__railFill",
  },
  badge: {
    root: "hero__badge",
    dot: "hero__badgeDot",
  },
  title: "hero__title",
  desc: "hero__desc",
}
