import {
  axiosLogo,
  comfyLogo,
  cssLogo,
  nodejsLogo,
  gdocsLogo,
  geminiLogo,
  ghatGPTLogo,
  github,
  gitLogo,
  grokLogo,
  htmlLogo,
  jsLogo,
  midjourneyLogo,
  perplexityLogo,
  postgresqlLogo,
  qwenLogo,
  reactRouterLogo,
  reduxLogo,
  sassLogo,
  soraLogo,
  sunoLogo,
  tailwindLogo,
  viteLogo,
  vsstudioLogo,
  reactLogo,
  claudeLogo,
  ollamaLogo,
  dockerLogo,
  n8nLogo,
  jiraLogo,
  notionLogo,
  gSheetsLogo,
  onecLogo,
  exelLogo,
  wordLogo,
  anydeskLogo,
  windowsLogo,
  ubuntuLogo,
  postmanLogo,
  jsonLogo,
  figmaLogo,
  aistudioLogo,
} from "@/shared/assets/icons"

export const resources = {
  html: { href: "https://developer.mozilla.org/docs/Web/HTML", logo: htmlLogo },
  css: { href: "https://developer.mozilla.org/docs/Web/CSS", logo: cssLogo },
  js: {
    href: "https://developer.mozilla.org/docs/Web/JavaScript",
    logo: jsLogo,
  },
  react: { href: "https://react.dev/", logo: reactLogo },
  reactRouter: { href: "https://reactrouter.com/", logo: reactRouterLogo },
  axios: { href: "https://axios-http.com/docs/api_intro", logo: axiosLogo },
  scss: { href: "https://sass-lang.com/", logo: sassLogo },
  tailwind: { href: "https://tailwindcss.com/", logo: tailwindLogo },
  figma: { href: "https://www.figma.com/", logo: figmaLogo },
  rtk: { href: "https://redux-toolkit.js.org/", logo: reduxLogo },
  vite: { href: "https://vite.dev/", logo: viteLogo },
  nodejs: { href: "https://nodejs.org/en", logo: nodejsLogo },
  postgres: { href: "https://www.postgresql.org/", logo: postgresqlLogo },
  json: { href: "https://www.json.org/json-ru.html", logo: jsonLogo },
  postman: { href: "https://www.postman.com/", logo: postmanLogo },
  windows: {
    href: "https://www.microsoft.com/en-us/windows/",
    logo: windowsLogo,
  },
  ubuntu: { href: "https://ubuntu.com/", logo: ubuntuLogo },
  git: { href: "https://git-scm.com/", logo: gitLogo },
  github: { href: "https://github.com/", logo: github },
  docker: { href: "https://www.docker.com/", logo: dockerLogo },
  n8n: { href: "https://n8n.io/", logo: n8nLogo },
  chatgpt: { href: "https://chatgpt.com/", logo: ghatGPTLogo },
  perplexity: { href: "https://www.perplexity.ai/", logo: perplexityLogo },
  claude: { href: "https://claude.ai/", logo: claudeLogo },
  gemini: { href: "https://gemini.google.com/", logo: geminiLogo },
  grok: { href: "https://x.ai", logo: grokLogo },
  googleAIStudio: {
    href: "https://aistudio.google.com/",
    logo: aistudioLogo,
  },
  qwen: { href: "https://qwen.ai/home", logo: qwenLogo },
  ollama: { href: "https://ollama.com/", logo: ollamaLogo },
  comfy: { href: "https://www.comfy.org", logo: comfyLogo },
  midjourney: { href: "https://www.midjourney.com/home", logo: midjourneyLogo },
  veo3: { href: "https://aistudio.google.com/models/veo-3", logo: geminiLogo },
  sora: { href: "https://sora.com/", logo: soraLogo },
  suno: { href: "https://suno.com/", logo: sunoLogo },
  vscode: { href: "https://code.visualstudio.com/", logo: vsstudioLogo },
  gdocs: {
    href: "https://workspace.google.com/intl/ru/products/docs/",
    logo: gdocsLogo,
  },
  notion: { href: "https://www.notion.so/", logo: notionLogo },
  jira: { href: "https://www.atlassian.com/ru/software/jira", logo: jiraLogo },
  gsheets: {
    href: "https://workspace.google.com/intl/ru/products/sheets/",
    logo: gSheetsLogo,
  },
  excel: { href: "https://excel.cloud.microsoft/ru-ru/", logo: exelLogo },
  word: { href: "https://word.cloud.microsoft/ru-ru/", logo: wordLogo },
  anydesk: { href: "https://anydesk.com/ru", logo: anydeskLogo },
  onec: { href: "https://1c.ru/", logo: onecLogo },
}
